---
- secret:
    name: SECRET_DEFAULTS
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - Xguf9bWgEDcv0CN5v5oZQKf6aybQhCrP6mBWZ68kqC8rjB7wA32Uah6DK6Zd8xX8X6NKo
          72Z+Jm7NdTCK2ktpMnmSK57mGAniT0u3nVntqzwbcsL393zTIuHCg0GHqiVEnGIdcrFHF
          BY4jUk3QAKW/C3PMqTOUMJpvkjqtBUWmGXIsuZq36WEXBzBSo8vXQ/D6EtV4fe1B1+tqv
          +dTJ9jWgfiaIi+xXauuuNdXi2+toVrBoSPOannKt7O5h8pbWiUqmlyZ+ezrQQ8GubLpN/
          v9rxyJGJaLUhFtO+paivJjsklI9T2l+4PquN0bFhsggzM1IEbuPfNZmMHKaEH6fX8I4+h
          ptyCXYcFu6dALZ/sDo96Uzmkz+FmCMvRGddgYk3mnuEh0NJcZvXzTYxBYQZmtiThc36P8
          Neu7OId7LXakxfZb1ABc/rxdxW+7W7xqTz0GB6edUBy61lsul771UtlR2inLR5XnN3tWW
          h7bl7uiToLsB0jG1J7UTUIsE4zzipXtqseGymdm4vfgb0/tmSesgA0AcmYFyR7ierdWFC
          KZIHI27fDq9mCTeQf1kmmrFCVgzEdoyLMz5D/PtjLPNwFg/Tq5ogzRkZc66DGzLNSryrQ
          YA3lj0opO4Rp4n8+I2K+wpCyBgzklsQBF4U4TZRCLFRz6rzt6S0IIjiiqfNv3I=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - TUBvRTTZOMcyzHks1QqygwQRE2mwq/Euss8BL538Ao/b6z8htrPPUs6/bDJhbIxG92LzG
          bsFQZA30DouzlnmQ+4IsDxIeNwK74xhRpGttUcha/AiEoYjjUvRrvcKyF833gYrziFcO4
          bqD4cFcM7S6lZ6mdfhOBhnWzhdI7tq0dQo+mWAhQS9h3yivCZcUirWda02ciEyBVqwHge
          h8wuwLx42skHxleImnXsnRfem+hrNrnvtVUaUN5uEzNzARzBl+HAm3aYP5wXPUtjO9xk5
          B4POgMhZbWtJ8Y43hejX3nuMCw1UM0bJuYilxTFX8WjT0GViiezja9ocaszwXc7lN0KQe
          WOCDBfyHGHOmammzmgbLQgI7vDbEejq2+B3zzqDDDX544mZZBPECN3Bmkv9uFwxDLOJyW
          rd4sNwXUGiXrOm1+iSrr1TT2IH4cF7CM2MZ9ZvDlDZIYJyOaurJQzrsubxMp+qxFG1GzJ
          OhpDtQJT5gaJMQF3xSvEnTPy5Bmk//5EtOiu53I4ckW2C3a91ATaZUuTIiSBztkyPKrvP
          vQabN+eWGB2+DveoLuZhyCzaRI/UKcUaE/H6GOzi2DOrA5mVOPdv/KJSF+3Oso1Z0yFgD
          RrBUW/DXvIoZq6yVAWpYpWns2JiltFLJMeeTqbBqKT/D9CjHIJt1wlvTr1J7Ks=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - C4Tq6rFUaY4qdPrLmDiCkRfvAuNR1Z99FEWeBPXwPl3KyoQCEOiQcPzWn9OEH05ZapNh8
          UR1K6r7NfqqxEbQTug2ri0vwIqANDihXKnnRFpY7vOXUrNqIIvsuzM4szxv62haCgpoTi
          TPfCSTz1XX9oa7o28Vn62m4wbDmFRKkTjvdkV1EwEbvQhvN+oPWD7zeKXNLuLZnwkjLjF
          o7JQi6erNMp7d6UicUrquLotF/54kP7E/sUjlk4vlBkdSY0RXmeqUFb1zkk4DgLaSGmPG
          cOJZg4D88nlcSQ4fpiqAGobVZFxOsW/JCMaOGckviIarUzYQVvp5Jdfg3hB32WsiRNHOw
          NDo2DIWQreRJDpIH6vfgMTzDNphcg6yw1nx2szhlBpQ3XxEx81uA1E7XsZFued9n/z+GZ
          oJ0N/99OgHV5Q7b5M8vUxpI5EJ9BraeMEfQh/oc8cE6cGaph8gkFm9owzB5WxsSefYgO3
          GWMQYRoxo7sc4CPmrTlFWc7p6/ztsQpCIToHxnixEMivTIoS1YRbM5udkZRgB1pyPz8B5
          pSeD089NutylvhMM1MkMaLk2AoQCi31pTyNPUmDndvXzNo1ukEnj8Y+R+E+iX+qtMhOAt
          qsfun0/fnuDK79hIsmfAqd1pkqmvY9UZRpxqoKRxHjsTlIupxB0WDijx64hAMc=

- job:
    name: defaults-container-image-inventory-reconciler-push
    parent: abstract-container-image-inventory-reconciler-push
    secrets:
      - name: secret
        secret: SECRET_DEFAULTS
        pass-to-parent: true

- job:
    name: defaults-container-image-osism-ansible-push
    parent: abstract-container-image-osism-ansible-push
    secrets:
      - name: secret
        secret: SECRET_DEFAULTS
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - yamllint
    gate:
      jobs:
        - yamllint
    periodic-daily:
      jobs:
        - yamllint
    post:
      jobs:
        - defaults-container-image-inventory-reconciler-push:
            branches: main
        - defaults-container-image-osism-ansible-push:
            branches: main
